StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {

        //db kullancağımız için dbnin injectesi
        private readonly IServiceManager _manager;



        //* Cart'ı injecte et
        private readonly Cart _cart;

        public OrderController(IServiceManager manager, Cart cart)
        {
            _manager = manager;
            _cart = cart;
        }

        public ViewResult Checkout() => View(new Order());


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if (_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your cart is empty.");
            }

            if (ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _cart.Clear();

                return RedirectToPage("/Complete", new { OrderId = order.OrderId });
            }

            else
            {
                return View();
            }


        }
    }
}

StoreApp/Pages/Cart.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;
using StoreApp.Infrastructure.Extensions;

namespace StoreApp.Pages
{
    public class CartModel : PageModel
    {
        public Cart Cart { get; set; }       //IoC 

        private readonly IServiceManager _manager;


        public CartModel(IServiceManager manager, Cart cartService)
        {
            _manager = manager;
            Cart = cartService;
        }

        public string ReturnUrl { get; set; } = "/";


        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/"; //referans yoksa "/" a git




            //* VARSA OLAN CART'I al YOKSA ÜRET
            //   Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }



        public IActionResult OnPost(int productId, string returnUrl)
        {
            Product? product = _manager.ProductService.GetOneProduct(productId, false);


            if (product is not null)
            {
                //     Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
                Cart.AddItem(product, 1);
                //*
                //    HttpContext.Session.SetJson<Cart>("cart", Cart);
            }

            return RedirectToPage(new { returnUrl = returnUrl }); //return url

        }

        //asp-page-handler
        public IActionResult OnPostRemove(int id, string returnUrl)
        {

            //     Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();

            Cart.RemoveLine(Cart.Lines.First(cl => cl.Product.ProductId.Equals(id)).Product);
            //   HttpContext.Session.SetJson<Cart>("cart", Cart);
            return Page();
        }



    }



}

StoreApp/Pages/Demo.cshtml.cs
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages

{
    public class DemoModel : PageModel
    {

        public String? FullName => HttpContext?.Session?.GetString("name") ?? "NoName";






        public void OnGet()
        {

        }
        //* parametrede model binding yapılcak
        public void OnPost([FromForm] string name)
        {
            //* name değerini class üzerinde değil session üzerinde tutucağız
            //  FullName = name;


            //* parametreden gelen değeri sesionda sakla
            HttpContext.Session.SetString("name", name);




        }

    }
}

StoreApp/Pages/Cart.cshtml
@page "/cart"

@model CartModel

<div>
    <div class="text-center display-6">
        Cart
    </div>

    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var line in Model.Cart?.Lines ?? Enumerable.Empty<CartLine>())
                {
      <tr>
        <td>@line.Product.ProductName</td>
        <td>@line.Quantity</td>
        <td>@line.Product.Price.ToString("c0")</td>
        <td>@((line.Product.Price * line.Quantity).ToString("c0"))</td>
        <td>
            <form method="post" asp-page-handler="Remove">
           <input type="hidden" name="id" value="@line.Product.ProductId"/>
           <input type="hidden" name="returnUrl" value="@Model.ReturnUrl"/>
           <button type="submit" class="btn btn-sm btn-danger ">
            <i class="fa fa-trash"></i>
           </button>
            </form>
        </td>
      </tr>
                }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-end ">Total :</td>
                <td class="text-end text-danger ">
                    @Model.Cart?.ComputeTotalValue().ToString("c0");
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="text-center my-3">
 <div class="btn-group ">
    <a class="btn btn-dark" href="@Model?.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-dark mx-2" asp-action="CheckOut" asp-controller="Order">
        Checkout
    </a>
 </div>
    </div>
</div>

StoreApp/Pages/Complete.cshtml
@page

<div class="text-center ">

    <h4 class="display-6 ">Thank you</h4>
    <p>Thanks for placing order #@OrderId</p>

    <p>We will ship your goods as soon as possible.</p>
    <a class="btn btn-dark" asp-controller="home" asp-action="index">
        Return to Store
    </a>
</div>


@functions {
    [BindProperty(SupportsGet = true)]
    public String? OrderId { get; set; }
}

StoreApp/Pages/Contact.cshtml
@page



<div class="text-center my-5 shadow rounded-3 bg-dark-subtle     p-5">


    <div class="display-6  text-dark mb-5  ">Contact</div>
    <div class="lead text-dark ">


        <h3> <i class="fa fa-phone"> </i> İletişim</h3>
        <h1 class="h-4 text-dark mb-5 "> +83838383</h1>
        <h1 class="fa fa-envelope text-dark"></h1>
        <h1 class> ecommarce@mail.com</h1>
    </div>



</div>

StoreApp/Pages/Demo.cshtml
@page

@model DemoModel


<div class="text-center my-5">
    <div class="display-6">Hello @HttpContext.Session.GetString("name") </div>

    <form method="post" asp-page="/demo">
        <div>
            <input class="" name="name" />

            <input type="submit" class="btn btn-dark" />
        </div>
    </form>
</div>