StoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components

{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;

        }


        public string Invoke()
        {
            return _cart.Lines.Count().ToString();
        }

    }

}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;


namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;




        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }









        public string Invoke()
        {
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
        }














    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;
using Services;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        /*  private readonly IRepositoryManager _manager;

         public CategoryController(IRepositoryManager manager)
         {
             _manager = manager;
         }
  */


        private readonly IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }


        /*   public IEnumerable<Category> Index()
          {
              return _manager.Category.FindAll(false);
          } */

        public IActionResult Index()
        {
            var model = _manager.CategoryService.GetAllCategories(false).ToList();
            return View(model);
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);

            return View(model);
        }
    }
}

StoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center ">

                    <br />

                </div>
                <div class="text-muted text-center">

                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2023 <br />HepsiBurada
                </div>

                <div class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>

            </div>
            <div class="col-md-2">
                <div products="" number="2"></div>
            </div>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>



<body>
    <nav>
        <partial name="_Navbar" />
        @RenderSection("_Navbar", false)

    </nav>
    <div class="container">


        <main role="main" class=pb-3"">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("_Footer", false)
        <partial name="_Footer" />
    </footer>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>



</html>

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="home" asp-action="index">
            <i class="fa fa-shop"></i>
            BG
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="home" asp-action="index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Category">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Product">Products
                        @* view component *@
                        (@await Component.InvokeAsync("ProductSummary"))
                    </a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="/Contact">
                        Contact
                    </a>

                </li>



                @* <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Dropdown
                </a>
                <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li>
                <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
                </li>
                *@

                @* <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li> *@


            </ul>
            <a class="btn" asp-area="admin" asp-controller="dashboard">Admin</a>
            <a class="btn " asp-page="/cart">
                <i class="fa fa-shopping-cart"></i>
                Cart (@await Component.InvokeAsync("CartSummary")) </a>



            @*
            <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
            </form> *@



        </div>
    </div>
</nav>

StoreApp/Views/Shared/_ProductCard.cshtml
@model Product















<div class="col-md-6 col-lg-6 ">
    <div class="card text-center  mx-auto my-3 " style="width: 18rem;  ">
        <div class="card-header bg-warning-subtle  text-center ">
            <h5 class="card-title">@Model.ProductName</h5>

        </div>

        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">

        <div class="card-body">

            <p class="card-text fs-3 ">@Model.Price.ToString("c2")</p>




            <div class="btn btn-group  ">

                <a class="btn btn-primary   " asp-controller="Product" asp-action="Get"
                    asp-route-id="@Model?.ProductId">

                    <i class="fas fa-arrow-right"></i>

                    Get details</a>
                <form id="@Model.ProductId" asp-page="/cart" method="post">

                    <input type="hidden" asp-for="ProductId" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />



                    <button type="submit" class="btn btn-outline-primary ">
                        <i class="fa fa-cart-plus"></i>

                    </button>
                </form>






            </div>


        </div>

    </div>



</div>